// Generated by Switchboard. You may edit this file.
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { revalidatePath } from "next/cache";
import { DeleteButton } from "@/components/form/DeleteButton";
import { PostResource } from "@/switchboard/generated/PostResource";
import { Prisma } from "@prisma/client";

type SearchParams = Record<string, string | string[] | undefined>;
type PageProps = { searchParams: Promise<SearchParams> };
type GeneratedColumn = {
  key: string;
  header?: string;
  format?: "datetime" | "date" | "boolean" | "json" | "relation";
  relationField?: string;
  relationLabelKey?: string;
};
const relationInclude = {
  author: { select: { id: true, name: true } },
} satisfies Prisma.PostInclude;
type ListRow = Prisma.PostGetPayload<{
  include: typeof relationInclude;
}>;

function actionErrorMessage(error: unknown, operation: "save" | "delete") {
  console.error(`Switchboard failed to ${operation} Post:`, error);
  if (error instanceof SyntaxError) {
    return "A JSON field contains invalid JSON.";
  }
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    if (error.code === "P2002") {
      return "A record with that unique value already exists.";
    }
    if (error.code === "P2003") {
      return operation === "delete"
        ? "This record cannot be deleted because other records still reference it."
        : "A selected related record no longer exists.";
    }
    if (error.code === "P2025") return "This record no longer exists.";
  }
  return operation === "delete"
    ? "The record could not be deleted."
    : "The record could not be saved. Check the values and try again.";
}

function displayValue(value: unknown, format?: GeneratedColumn["format"]) {
  if (value === null || value === undefined || value === "") {
    return <span className="sb-null-value">Not set</span>;
  }
  if (format === "boolean") return value ? "Yes" : "No";
  if (format === "datetime" || format === "date") {
    const date = value instanceof Date ? value : new Date(String(value));
    if (Number.isNaN(date.getTime())) return String(value);
    return format === "date"
      ? date.toLocaleDateString()
      : date.toLocaleString();
  }
  if (format === "json" || typeof value === "object") {
    try {
      return JSON.stringify(value);
    } catch {
      return String(value);
    }
  }
  return String(value);
}

export default async function PostListPage({ searchParams }: PageProps) {
  const params = await searchParams;
  const q = typeof params.q === "string" ? params.q.trim().slice(0, 200) : "";
  const requestedPage = Number(
    typeof params.page === "string" ? params.page : "1",
  );
  const safeRequestedPage =
    Number.isSafeInteger(requestedPage) && requestedPage > 0
      ? requestedPage
      : 1;
  const configuredTake = PostResource.list?.perPage ?? 20;
  const take = Math.min(100, Math.max(1, Math.trunc(configuredTake)));

  const supportedSearchFields = new Set(["title", "content"]);
  const searchable = (
    PostResource.list?.searchable ?? ["title", "content"]
  ).filter((field) => supportedSearchFields.has(field));
  const supportedSortFields = new Set([
    "id",
    "title",
    "content",
    "status",
    "createdAt",
    "updatedAt",
  ]);
  const sortable = (
    PostResource.list?.sortable ?? [
      "id",
      "title",
      "content",
      "status",
      "createdAt",
      "updatedAt",
    ]
  ).filter((field) => supportedSortFields.has(field));
  const configuredDefaultSort = PostResource.list?.defaultSort;
  const defaultSortKey =
    configuredDefaultSort && sortable.includes(configuredDefaultSort.key)
      ? configuredDefaultSort.key
      : "";
  const defaultSortDir: "asc" | "desc" =
    configuredDefaultSort?.dir === "asc" ? "asc" : "desc";
  const requestedSort = typeof params.sort === "string" ? params.sort : "";
  const sortKey = sortable.includes(requestedSort)
    ? requestedSort
    : defaultSortKey;
  const sortDir =
    params.dir === "asc" || params.dir === "desc" ? params.dir : defaultSortDir;
  const orderBy = (sortKey ? { [sortKey]: sortDir } : undefined) as
    | Prisma.PostOrderByWithRelationInput
    | undefined;
  const where = (
    q && searchable.length
      ? {
          OR: searchable.map((field) => ({
            [field]: { contains: q },
          })),
        }
      : {}
  ) as Prisma.PostWhereInput;

  const total = await prisma.post.count({ where });
  const totalPages = Math.max(1, Math.ceil(total / take));
  const page = Math.min(safeRequestedPage, totalPages);
  const items: ListRow[] = await prisma.post.findMany({
    where,
    orderBy,
    skip: (page - 1) * take,
    take,
    include: relationInclude,
  });
  const columns = (PostResource.list?.columns ?? [
    {
      key: "id",
      header: "Id",
    },
    {
      key: "title",
      header: "Title",
    },
    {
      key: "content",
      header: "Content",
    },
    {
      key: "status",
      header: "Status",
    },
    {
      key: "authorId",
      header: "Author",
      format: "relation",
      relationField: "author",
      relationLabelKey: "name",
    },
    {
      key: "createdAt",
      header: "Created At",
      format: "datetime",
    },
    {
      key: "updatedAt",
      header: "Updated At",
      format: "datetime",
    },
  ]) as readonly GeneratedColumn[];

  async function del(_previousState: { error?: string }, formData: FormData) {
    "use server";
    try {
      const rawId = formData.get("id");
      if (typeof rawId !== "string" || !rawId) {
        return { error: "The record identifier is missing." };
      }
      await prisma.post.delete({
        where: { id: rawId },
      });
    } catch (error) {
      return { error: actionErrorMessage(error, "delete") };
    }
    revalidatePath("/admin/posts");
    return {};
  }

  const queryString = (
    next: Partial<{
      page: number;
      sort: string;
      dir: "asc" | "desc";
    }>,
  ) => {
    const query = new URLSearchParams();
    if (q) query.set("q", q);
    query.set("page", String(next.page ?? page));
    const nextSort = next.sort ?? sortKey;
    if (nextSort && sortable.includes(nextSort)) {
      query.set("sort", nextSort);
      query.set("dir", next.dir ?? sortDir);
    }
    return `?${query.toString()}`;
  };

  const header = (column: GeneratedColumn) => {
    if (!sortable.includes(column.key)) {
      return column.header ?? column.key;
    }
    const active = sortKey === column.key;
    const nextDir = active && sortDir === "asc" ? "desc" : "asc";
    return (
      <a
        className="sb-action-link"
        href={queryString({
          page: 1,
          sort: column.key,
          dir: nextDir,
        })}
      >
        {column.header ?? column.key}
        {active ? (sortDir === "asc" ? " (asc)" : " (desc)") : ""}
      </a>
    );
  };

  return (
    <section className="sb-page">
      <div className="sb-page-header">
        <div>
          <p className="sb-eyebrow">Resource</p>
          <h1 className="sb-page-title">Posts</h1>
          <p className="sb-page-description">
            View, search, and manage post records.
          </p>
        </div>
        <Link href="/admin/posts/new" className="sb-button">
          + New
        </Link>
      </div>

      {searchable.length ? (
        <form method="get" className="sb-search-form">
          <input
            type="search"
            name="q"
            defaultValue={q}
            placeholder={"Search " + searchable.join(", ")}
            className="sb-input"
          />
          {sortKey ? <input type="hidden" name="sort" value={sortKey} /> : null}
          {sortKey ? <input type="hidden" name="dir" value={sortDir} /> : null}
          <button className="sb-button sb-button-secondary" type="submit">
            Search
          </button>
          {q ? (
            <Link className="sb-action-link" href="/admin/posts">
              Clear
            </Link>
          ) : null}
        </form>
      ) : null}

      <div className="sb-table-wrap">
        <table className="sb-table">
          <thead>
            <tr>
              {columns.map((column) => (
                <th key={column.key}>{header(column)}</th>
              ))}
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {items.map((row) => {
              const values = row as unknown as Record<string, unknown>;
              return (
                <tr key={String(values.id)}>
                  {columns.map((column) => {
                    const related =
                      column.format === "relation" && column.relationField
                        ? (values[column.relationField] as
                            | Record<string, unknown>
                            | null
                            | undefined)
                        : undefined;
                    const value =
                      related && column.relationLabelKey
                        ? related[column.relationLabelKey]
                        : values[column.key];
                    return (
                      <td key={column.key}>
                        {displayValue(value, column.format)}
                      </td>
                    );
                  })}
                  <td>
                    <div className="sb-actions">
                      <Link
                        className="sb-table-action"
                        href={
                          "/admin/posts/" +
                          encodeURIComponent(String(values.id)) +
                          "/edit"
                        }
                      >
                        Edit
                      </Link>
                      <DeleteButton
                        action={del}
                        idName="id"
                        idValue={String(values.id)}
                      />
                    </div>
                  </td>
                </tr>
              );
            })}
            {items.length === 0 ? (
              <tr>
                <td className="sb-empty-state" colSpan={columns.length + 1}>
                  {q
                    ? `No post records match "${q}".`
                    : "No post records yet. Create one to get started."}
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      <div className="sb-pagination">
        <span>
          Page {page} of {totalPages} ({total}{" "}
          {total === 1 ? "record" : "records"})
        </span>
        <div className="sb-pagination-actions">
          {page > 1 ? (
            <a
              className="sb-pagination-link"
              href={queryString({ page: page - 1 })}
            >
              Previous
            </a>
          ) : (
            <span className="sb-pagination-link sb-is-disabled">Previous</span>
          )}
          {page < totalPages ? (
            <a
              className="sb-pagination-link"
              href={queryString({ page: page + 1 })}
            >
              Next
            </a>
          ) : (
            <span className="sb-pagination-link sb-is-disabled">Next</span>
          )}
        </div>
      </div>
    </section>
  );
}
