// Generated by Switchboard. You may edit this file.
import { login } from "@/switchboard/auth-actions";

type LoginPageProps = {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
};

export default async function LoginPage({ searchParams }: LoginPageProps) {
  const params = await searchParams;
  const error = typeof params.error === "string" ? params.error : "";

  return (
    <main className="sb-login-card sb-card">
      <div>
        <p className="sb-eyebrow">Switchboard</p>
        <h1 className="sb-page-title">Admin login</h1>
        <p className="sb-page-description">
          Sign in with an administrator account.
        </p>
      </div>
      {error ? (
        <p className="sb-login-error" role="alert">
          {error === "missing"
            ? "Enter your username and password."
            : "Invalid credentials or administrator access is required."}
        </p>
      ) : null}
      <form action={login} className="sb-form sb-login-form">
        <label className="sb-form-field">
          <span className="sb-form-label">Username</span>
          <input
            autoComplete="username"
            autoFocus
            className="sb-form-control"
            name="credential"
            required
            type="text"
          />
        </label>
        <label className="sb-form-field">
          <span className="sb-form-label">Password</span>
          <input
            autoComplete="current-password"
            className="sb-form-control"
            name="password"
            required
            type="password"
          />
        </label>
        <div className="sb-form-actions">
          <button className="sb-button" type="submit">
            Sign in
          </button>
        </div>
      </form>
    </main>
  );
}
