// Generated by Switchboard. You may edit this file.
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { SmartForm } from "@/components/form/SmartForm";
import { ProjectResource } from "@/switchboard/generated/ProjectResource";

import { Prisma } from "@prisma/client";

function actionErrorMessage(error: unknown, operation: "save" | "delete") {
  console.error(`Switchboard failed to ${operation} Project:`, error);
  if (error instanceof SyntaxError) {
    return "A JSON field contains invalid JSON.";
  }
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    if (error.code === "P2002") {
      return "A record with that unique value already exists.";
    }
    if (error.code === "P2003") {
      return operation === "delete"
        ? "This record cannot be deleted because other records still reference it."
        : "A selected related record no longer exists.";
    }
    if (error.code === "P2025") return "This record no longer exists.";
  }
  return operation === "delete"
    ? "The record could not be deleted."
    : "The record could not be saved. Check the values and try again.";
}

export default async function NewProjectPage() {
  const [ownerRecords] = await Promise.all([
    prisma.user.findMany({
      select: {
        id: true,
        name: true,
      },
      orderBy: { name: "asc" },
    }),
  ]);
  const relationOptions = {
    ownerId: ownerRecords.map((record) => ({
      value: String(record.id),
      label: String(record.name ?? record.id),
    })),
  };

  async function create(
    _previousState: { error?: string },
    formData: FormData,
  ) {
    "use server";
    try {
      const data: Prisma.ProjectUncheckedCreateInput = {
        name: String(formData.get("name") ?? ""),
        description: formData.get("description")
          ? String(formData.get("description") ?? "")
          : null,
        status: formData.get("status")
          ? (String(
              formData.get("status") ?? "",
            ) as Prisma.ProjectUncheckedCreateInput["status"])
          : undefined,
        ownerId: formData.get("ownerId")
          ? String(formData.get("ownerId") ?? "")
          : null,
      };
      await prisma.project.create({ data });
    } catch (error) {
      return { error: actionErrorMessage(error, "save") };
    }
    revalidatePath("/admin/projects");
    redirect("/admin/projects");
  }

  return (
    <SmartForm
      title="New Project"
      fields={ProjectResource.fields}
      relationOptions={relationOptions}
      submitLabel="Create"
      cancelHref="/admin/projects"
      action={create}
    />
  );
}
