// Generated by Switchboard. You may edit this file.
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { SmartForm } from "@/components/form/SmartForm";
import { UserResource } from "@/switchboard/generated/UserResource";
import { hashPassword } from "@/switchboard/auth";
import { Prisma } from "@prisma/client";

type PageProps = { params: Promise<{ id: string }> };

function actionErrorMessage(error: unknown, operation: "save" | "delete") {
  console.error(`Switchboard failed to ${operation} User:`, error);
  if (error instanceof SyntaxError) {
    return "A JSON field contains invalid JSON.";
  }
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    if (error.code === "P2002") {
      return "A record with that unique value already exists.";
    }
    if (error.code === "P2003") {
      return operation === "delete"
        ? "This record cannot be deleted because other records still reference it."
        : "A selected related record no longer exists.";
    }
    if (error.code === "P2025") return "This record no longer exists.";
  }
  return operation === "delete"
    ? "The record could not be deleted."
    : "The record could not be saved. Check the values and try again.";
}

export default async function EditUserPage({ params }: PageProps) {
  const routeParams = await params;
  const id = routeParams.id;
  const [existing] = await Promise.all([
    prisma.user.findUnique({ where: { id: id } }),
  ]);
  if (!existing) {
    return <div className="sb-card sb-empty-state">Record not found.</div>;
  }
  const relationOptions = {};

  async function update(
    _previousState: { error?: string },
    formData: FormData,
  ) {
    "use server";
    try {
      const data: Prisma.UserUncheckedUpdateInput = {
        name: String(formData.get("name") ?? ""),
        username: formData.get("username")
          ? String(formData.get("username") ?? "")
          : null,
        email: String(formData.get("email") ?? ""),
        passwordHash: formData.get("passwordHash")
          ? await hashPassword(String(formData.get("passwordHash") ?? ""))
          : undefined,
        role: formData.get("role")
          ? (String(
              formData.get("role") ?? "",
            ) as Prisma.UserUncheckedUpdateInput["role"])
          : undefined,
      };
      await prisma.user.update({
        where: { id: id },
        data,
      });
    } catch (error) {
      return { error: actionErrorMessage(error, "save") };
    }
    revalidatePath("/admin/users");
    redirect("/admin/users");
  }

  const jsonFields = new Set<string>([]);
  const initialValues = Object.fromEntries(
    Object.entries(existing).map(([key, value]) => [
      key,
      ["password", "passwordHash"].includes(key)
        ? ""
        : value instanceof Date
          ? value.toISOString().slice(0, 16)
          : typeof value === "bigint"
            ? String(value)
            : jsonFields.has(key) && value !== null
              ? JSON.stringify(value, null, 2)
              : value,
    ]),
  );

  return (
    <SmartForm
      title="Edit User"
      fields={UserResource.fields}
      initialValues={initialValues}
      relationOptions={relationOptions}
      submitLabel="Save"
      cancelHref="/admin/users"
      action={update}
    />
  );
}
