import chalk from "chalk";
import fs from "fs-extra";
import path from "path";

import { adminLayoutTemplate } from "../../templates/adminLayout.js";
import { parsePrismaSchema } from "../parser/prismaSchemaParser.js";
import { detectGenerationLayout } from "../project/detectProject.js";
import { importPath } from "../project/importPath.js";
import {
  applyFileAction,
  describeFileAction,
  GENERATED_FILE_MARKER,
  GENERATED_REGISTRY_MARKER,
  hasGeneratedFileMarker,
  planFileAction,
} from "../utils/fileActions.js";
import { formatTypeScript, relativePath } from "../utils/fs.js";

function isSwitchboardRegistry(content) {
  return (
    hasGeneratedFileMarker(content) ||
    content.includes("Auto-generated by Switchboard CLI") ||
    /export const resources:\s*ResourceConfig\[\]\s*=\s*\[\s*\];/.test(content)
  );
}

export async function generateProject({
  projectRoot = process.cwd(),
  model,
  pages = false,
  schemaPath: schemaOption,
  out,
  appDir: appDirOption,
  force = false,
  dryRun = false,
  log = (message) => console.log(chalk.green(message)),
} = {}) {
    const options = { model, pages };
    const detectedLayout = detectGenerationLayout({
      projectRoot,
      schemaPath: schemaOption,
      appDir: appDirOption,
      out,
    });
    const {
      projectRoot: resolvedProjectRoot,
      appDir,
      schemaPath,
      libDir,
      componentsDir,
      outDir,
      generatedDir: genDir,
    } = detectedLayout;
    const results = [];

    if (dryRun) {
      log("Detected project structure:");
      log(`  App directory: ${relativePath(resolvedProjectRoot, appDir)}`);
      log(`  Prisma schema: ${relativePath(resolvedProjectRoot, schemaPath)}`);
      log(
        `  Source root: ${relativePath(resolvedProjectRoot, detectedLayout.sourceRoot) || "."}`,
      );
      log(
        detectedLayout.importAlias
          ? `  Import alias: ${detectedLayout.importAlias.pattern} -> ${detectedLayout.importAlias.target}`
          : "  Import alias: none (using relative imports)",
      );
      log(`  Output directory: ${relativePath(resolvedProjectRoot, outDir)}`);
    }

    const writeGeneratedFile = async (
      filePath,
      source,
      { allowUpdate = false, isSafeToUpdate } = {},
    ) => {
      const content = await formatTypeScript(source);
      const plan = await planFileAction({
        path: filePath,
        content,
        force,
        allowUpdate,
        isSafeToUpdate,
      });
      const displayPath = relativePath(resolvedProjectRoot, filePath);
      results.push({ action: plan.action, path: displayPath });
      await applyFileAction(plan, { dryRun });
      log(describeFileAction(plan, displayPath, { dryRun }));
      return plan;
    };

    const schema = await fs.readFile(schemaPath, "utf8");

    const { enums, models } = parsePrismaSchema(schema, schemaPath);

    // Helpers
    const baseType = (t) => t.replace(/\?$/, "").replace(/\[\]$/, "");
    const isOptional = (t) => t.endsWith("?");
    const isArray = (t) => t.replace(/\?$/, "").endsWith("[]");
    const hasDefault = (field) =>
      /(?:^|\s)@default\s*\(/.test(field.attrs);
    const isUpdatedAt = (field) =>
      /(?:^|\s)@updatedAt(?:\s|$)/.test(field.attrs);
    const scalarTypes = new Set([
      "String",
      "Int",
      "Float",
      "Decimal",
      "BigInt",
      "Boolean",
      "DateTime",
      "Json",
      "Bytes",
    ]);
    const isScalarField = (field) => {
      const type = baseType(field.type);
      return !isArray(field.type) && (scalarTypes.has(type) || Boolean(enums[type]));
    };
    const formValueFor = (field, prismaInputType, mode) => {
      const type = baseType(field.type);
      const value = `formData.get("${field.name}")`;
      const stringValue = `String(${value} ?? "")`;
      const emptyValue = hasDefault(field)
        ? "undefined"
        : isOptional(field.type)
          ? "null"
          : '""';

      if (["password", "passwordHash"].includes(field.name)) {
        return mode === "edit"
          ? `${value} ? await hashPassword(${stringValue}) : undefined`
          : `await hashPassword(${stringValue})`;
      }
      if (enums[type]) {
        const enumValue = `${stringValue} as ${prismaInputType}["${field.name}"]`;
        return hasDefault(field) || isOptional(field.type)
          ? `${value} ? ${enumValue} : ${emptyValue}`
          : enumValue;
      }
      switch (type) {
        case "Int":
        case "Float":
        case "Decimal":
          return isOptional(field.type) || hasDefault(field)
            ? `${value} ? Number(${value}) : ${emptyValue}`
            : `Number(${value})`;
        case "BigInt":
          return isOptional(field.type) || hasDefault(field)
            ? `${value} ? BigInt(${stringValue}) : ${emptyValue}`
            : `BigInt(${stringValue})`;
        case "Boolean":
          return `formData.has("${field.name}")`;
        case "DateTime":
          return isOptional(field.type) || hasDefault(field)
            ? `${value} ? new Date(${stringValue}) : ${emptyValue}`
            : `new Date(${stringValue})`;
        case "Json":
          return `${value} ? JSON.parse(${stringValue}) : ${emptyValue}`;
        case "Bytes":
          return `Buffer.from(${stringValue})`;
        default:
          return isOptional(field.type) || hasDefault(field)
            ? `${value} ? ${stringValue} : ${emptyValue}`
            : stringValue;
      }
    };
    const tsTypeFor = (prismaTypeRaw) => {
      const base = baseType(prismaTypeRaw);
      let ts;
      switch (base) {
        case "String":
          ts = "string";
          break;
        case "Int":
        case "Float":
        case "Decimal":
          ts = "number";
          break;
        case "BigInt":
          ts = "string";
          break;
        case "Boolean":
          ts = "boolean";
          break;
        case "DateTime":
          ts = "string"; // form-friendly
          break;
        case "Json":
          ts = "unknown";
          break;
        default:
          ts = enums[base]
            ? enums[base].map((v) => JSON.stringify(v)).join(" | ")
            : "unknown";
      }
      if (isArray(prismaTypeRaw)) ts = `${ts}[]`;
      return ts;
    };
    const widgetFor = (fieldName, prismaTypeRaw, modelFields) => {
      const b = baseType(prismaTypeRaw);

      // Heuristic: relation if field ends with 'Id' and a sibling object field matches (e.g., authorId + author User)
      if (/Id$/.test(fieldName)) {
        const guessModel = fieldName.replace(/Id$/, "");
        const objectField = modelFields.find((mf) => baseType(mf.type) === guessModel[0].toUpperCase() + guessModel.slice(1));
        if (objectField) {
          return { type: "relation", model: (objectField.type.replace(/\?$/, "")) };
        }
      }

      if (enums[b]) {
        return { type: "select", options: enums[b].map((v) => ({ value: v, label: v })) };
      }
      if (b === "Boolean") return { type: "checkbox" };
      if (b === "DateTime") return { type: "datetime" };
      if (b === "String" && /content|description|body/i.test(fieldName)) {
        return { type: "textarea", rows: 8 };
      }
      if (b === "String" && /^(?:password|passwordHash)$/i.test(fieldName)) {
        return { type: "password" };
      }
      if (b === "String" && /email/i.test(fieldName)) return { type: "email" };
      return { type: "text" };
    };
    const pageModels = options.model
      ? models.filter((model) => model.name === options.model)
      : models;
    if (options.model && pageModels.length === 0) {
      throw new Error(
        `Model "${options.model}" was not found in Prisma schema "${schemaPath}".`,
      );
    }

    if (options.pages) {
      const supportedIdTypes = new Set(["String", "Int", "BigInt"]);
      for (const model of pageModels) {
        if (model.compoundIdFields.length > 0) {
          throw new Error(
            `Cannot generate admin pages for model "${model.name}": compound IDs ` +
              `(@@id([${model.compoundIdFields.join(", ")}])) are not supported. ` +
              "Use a single String, Int, or BigInt @id field, or run without --pages.",
          );
        }
        if (model.idFields.length !== 1 || !model.idField) {
          throw new Error(
            `Cannot generate admin pages for model "${model.name}": expected one explicit scalar @id field. ` +
              "Add a single String, Int, or BigInt @id field, or run without --pages.",
          );
        }
        const idType = baseType(model.idField.type);
        if (!isScalarField(model.idField) || !supportedIdTypes.has(idType)) {
          throw new Error(
            `Cannot generate admin pages for model "${model.name}": primary key ` +
              `"${model.idField.name}" has unsupported type "${model.idField.type}". ` +
              "Use a single String, Int, or BigInt @id field, or run without --pages.",
          );
        }
      }
    }

    // Generate configs and pages
    for (const model of models) {
      if (options.model && options.model !== model.name) continue;

      const fieldsForUI = model.fields.filter(
        (f) =>
          !(f === model.idField && hasDefault(f)) &&
          !isUpdatedAt(f) &&
          !(
            ["createdAt", "updatedAt"].includes(f.name) &&
            hasDefault(f)
          ) &&
          isScalarField(f)
      );

      // generated ResourceConfig
      const shapeProps = fieldsForUI
        .map(
          (f) =>
            `  ${f.name}${isOptional(f.type) || hasDefault(f) ? "?" : ""}: ${tsTypeFor(f.type)};`
        )
        .join("\n");

      const resourceFields = fieldsForUI.map((f) => ({
        name: f.name,
        label: f.name[0].toUpperCase() + f.name.slice(1),
        required: !isOptional(f.type) && !hasDefault(f),
        widget: widgetFor(f.name, f.type, model.fields),
      }));

      const configObject = {
        resource: model.name,
        displayName: model.name + "s",
        fields: resourceFields,
        list: {
          perPage: 20,
          searchable: fieldsForUI
            .filter(
              (f) =>
                ["String"].includes(baseType(f.type)) &&
                !["password", "passwordHash"].includes(f.name),
            )
            .map((f) => f.name),
          columns: fieldsForUI
            .filter((f) => !["password", "passwordHash"].includes(f.name))
            .map((f) => ({
              key: f.name,
              header: f.name[0].toUpperCase() + f.name.slice(1),
              format: baseType(f.type) === "DateTime" ? "datetime" : baseType(f.type) === "Boolean" ? "boolean" : undefined
            })),
          defaultSort: model.hasCreatedAt ? { key: "createdAt", dir: "desc" } : undefined,
        },
      };
      const resourcePath = path.join(genDir, `${model.name}Resource.ts`);
      const typesPath = path.join(outDir, "types.ts");

      const configFile = `
        // ${GENERATED_FILE_MARKER}
        import type { ResourceConfig } from "${importPath(detectedLayout, resourcePath, typesPath)}";

        export type ${model.name}Shape = {
${shapeProps}
        };

        export const ${model.name}Resource: ResourceConfig<${model.name}Shape> =
          ${JSON.stringify(configObject, null, 2)} as const;
      `;
      await writeGeneratedFile(resourcePath, configFile);

      if (!options.pages) continue;

// admin pages
const plural = model.name.toLowerCase() + "s";
const adminDir = path.join(appDir, "admin", plural);

// ensure all nested route dirs exist
const newDir = path.join(adminDir, "new");
const idDir = path.join(adminDir, "[id]");
const editDir = path.join(idDir, "edit");
const listPagePath = path.join(adminDir, "page.tsx");
const newPagePath = path.join(newDir, "page.tsx");
const editPagePath = path.join(editDir, "page.tsx");
const prismaPath = path.join(libDir, "prisma.ts");
const smartFormPath = path.join(componentsDir, "form", "SmartForm.tsx");
const simpleTablePath = path.join(
  componentsDir,
  "table",
  "SimpleTable.tsx",
);
const authPath = path.join(outDir, "auth.ts");
const hasPasswordField = fieldsForUI.some((field) =>
  ["password", "passwordHash"].includes(field.name),
);

const idName = model.idField?.name ?? "id";
const idTypeBase = baseType(model.idField?.type ?? "String");

const listPage = `
  // ${GENERATED_FILE_MARKER}
  import { prisma } from "${importPath(detectedLayout, listPagePath, prismaPath)}";
  import Link from "next/link";
  import { revalidatePath } from "next/cache";
  import { ${model.name}Resource } from "${importPath(detectedLayout, listPagePath, resourcePath)}";
  import type { Column } from "${importPath(detectedLayout, listPagePath, simpleTablePath)}";
  import type { ${model.name}, Prisma } from "@prisma/client";

  type SearchParams = Record<string, string | string[] | undefined>;
  type PageProps = { searchParams: Promise<SearchParams> };

  export default async function ${model.name}ListPage({ searchParams }: PageProps) {
    const params = await searchParams;
    const q = typeof params.q === "string" ? params.q.trim() : "";
    const page = Number(params.page ?? 1) || 1;
    const take = ${model.name}Resource.list?.perPage ?? 20;
    const skip = (page - 1) * take;

    // Sorting
    const defaultSortKey = ${JSON.stringify(model.hasCreatedAt ? "createdAt" : "")};
    const defaultSortDir: "asc" | "desc" = ${JSON.stringify(model.hasCreatedAt ? "desc" : "asc")};
    const sortKey = typeof params.sort === "string" ? params.sort : defaultSortKey;
    const sortDir =
      params.dir === "asc" || params.dir === "desc"
        ? params.dir
        : defaultSortDir;
    const orderBy = (sortKey ? { [sortKey]: sortDir } : ${model.hasCreatedAt ? `{ createdAt: "desc" }` : "undefined"}) as Prisma.${model.name}OrderByWithRelationInput | undefined;

    // Search
    const searchable = ${model.name}Resource.list?.searchable ?? [];
    const where = (q && searchable.length
      ? { OR: searchable.map((field) => ({ [field]: { contains: q } })) }
      : {}) as Prisma.${model.name}WhereInput;

    const [items, total] = await Promise.all([
      prisma.${model.name.toLowerCase()}.findMany({
        where,
        orderBy,
        skip,
        take,
      }),
      prisma.${model.name.toLowerCase()}.count({ where }),
    ]);

    type GeneratedColumn = {
      key: string;
      header?: string;
      format?: "datetime" | "date" | "boolean";
    };
    const generatedColumns = (${model.name}Resource.list?.columns ?? ${JSON.stringify(
        (resourceFields || []).map((f) => ({ key: f.name, header: f.label })),
        null,
        2
      )}) as readonly GeneratedColumn[];

    const columns: Column<${model.name}>[] = generatedColumns.map((column) => {
      const baseColumn: Column<${model.name}> = {
        key: column.key,
        header: column.header,
      };
      if (column.format === "datetime") {
        return { ...baseColumn, cell: (row) => new Date(String((row as unknown as Record<string, unknown>)[column.key])).toLocaleString() };
      }
      if (column.format === "date") {
        return { ...baseColumn, cell: (row) => new Date(String((row as unknown as Record<string, unknown>)[column.key])).toLocaleDateString() };
      }
      if (column.format === "boolean") {
        return { ...baseColumn, cell: (row) => ((row as unknown as Record<string, unknown>)[column.key] ? "Yes" : "No") };
      }
      return baseColumn;
    });

    async function del(formData: FormData) {
      "use server";
      const id = String(formData.get("${idName}"));
      await prisma.${model.name.toLowerCase()}.delete({
        where: { ${idName}: ${idTypeBase === "Int" ? "Number(id)" : idTypeBase === "BigInt" ? "BigInt(id)" : "id"} }
      });
      revalidatePath("/admin/${plural}");
    }

    const totalPages = Math.max(1, Math.ceil(total / take));

    const qs = (next: Record<string,string|number>) => {
      const p = new URLSearchParams();
      if (q) p.set("q", q);
      p.set("page", String(next.page ?? page));
      p.set("sort", String(next.sort ?? sortKey));
      p.set("dir", String(next.dir ?? sortDir));
      return \`?\${p.toString()}\`;
    };

    const headerLink = (key: string, label?: string) => {
      const active = sortKey === key;
      const nextDir = active && sortDir === "asc" ? "desc" : "asc";
      const base = \`/admin/${plural}\${qs({ page: 1, sort: key, dir: active ? nextDir : "asc" })}\`;
      return (
        <a href={base} className="sb-action-link">
          {label ?? key}
          {active ? (sortDir === "asc" ? " (asc)" : " (desc)") : ""}
        </a>
      );
    };

    return (
      <section className="sb-page">
        <div className="sb-page-header">
          <div>
            <p className="sb-eyebrow">Resource</p>
            <h1 className="sb-page-title">${model.name}s</h1>
            <p className="sb-page-description">View, search, and manage ${model.name.toLowerCase()} records.</p>
          </div>
          <Link
            href="/admin/${plural}/new"
            className="sb-button"
          >
            + New
          </Link>
        </div>

        {/* Search */}
        <form method="get" className="sb-search-form">
          <input
            type="text"
            name="q"
            defaultValue={q}
            placeholder={"Search " + (${model.name}Resource.list?.searchable ?? []).join(", ")}
            className="sb-input"
          />
          <input type="hidden" name="sort" value={sortKey} />
          <input type="hidden" name="dir" value={sortDir} />
          <button className="sb-button sb-button-secondary" type="submit">Search</button>
        </form>

        <div className="sb-table-wrap">
          <table className="sb-table">
            <thead>
              <tr>
                {columns.map((c) => (
                  <th key={String(c.key)}>
                    {headerLink(String(c.key), c.header)}
                  </th>
                ))}
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {items.map((row) => (
                <tr key={String((row as unknown as Record<string, unknown>).${idName})}>
                  {columns.map((c) => (
                    <td key={String(c.key)}>
                      {c.cell ? c.cell(row) : String((row as unknown as Record<string, unknown>)[c.key] ?? "")}
                    </td>
                  ))}
                  <td>
                    <div className="sb-actions">
                      <Link className="sb-action-link" href={"/admin/${plural}/" + String((row as unknown as Record<string, unknown>).${idName}) + "/edit"}>Edit</Link>
                      <form action={del}>
                        <input type="hidden" name="${idName}" value={String((row as unknown as Record<string, unknown>).${idName})} />
                        <button type="submit" className="sb-button-danger">Delete</button>
                      </form>
                    </div>
                  </td>
                </tr>
              ))}
              {items.length === 0 && (
                <tr><td className="sb-empty-state" colSpan={columns.length + 1}>No records found.</td></tr>
              )}
            </tbody>
          </table>
        </div>

                {/* Pagination */}
        <div className="sb-pagination">
          <span>Page {page} of {totalPages}</span>
          <div className="sb-pagination-actions">
            <a
              className={\`sb-pagination-link \${page <= 1 ? "sb-is-disabled" : ""}\`}
              href={qs({ page: Math.max(1, page - 1) })}
            >
              Prev
            </a>
            <a
              className={\`sb-pagination-link \${page >= totalPages ? "sb-is-disabled" : ""}\`}
              href={qs({ page: Math.min(totalPages, page + 1) })}
            >
              Next
            </a>
          </div>
        </div>
      </section>
    );
  }
`;

      // new page — SmartForm + redirect
      const newPage = `
        // ${GENERATED_FILE_MARKER}
        import { prisma } from "${importPath(detectedLayout, newPagePath, prismaPath)}";
        import { revalidatePath } from "next/cache";
        import { redirect } from "next/navigation";
        import { SmartForm } from "${importPath(detectedLayout, newPagePath, smartFormPath)}";
        import { ${model.name}Resource } from "${importPath(detectedLayout, newPagePath, resourcePath)}";
        ${hasPasswordField ? `import { hashPassword } from "${importPath(detectedLayout, newPagePath, authPath)}";` : ""}
        import type { Prisma } from "@prisma/client";

        export default function New${model.name}Page() {
          async function create(formData: FormData) {
            "use server";
            const data: Prisma.${model.name}UncheckedCreateInput = {
${fieldsForUI
  .map(
    (field) =>
      `              ${field.name}: ${formValueFor(
        field,
        `Prisma.${model.name}UncheckedCreateInput`,
        "create",
      )},`
  )
  .join("\n")}
            };
            await prisma.${model.name.toLowerCase()}.create({ data });
            revalidatePath("/admin/${plural}");
            redirect("/admin/${plural}");
          }

          return (
            <SmartForm
              title="New ${model.name}"
              fields={${model.name}Resource.fields}
              submitLabel="Create"
              cancelHref="/admin/${plural}"
              action={create}
            />
          );
        }
      `;

      // edit page — ID type respected
      const editPage = `
        // ${GENERATED_FILE_MARKER}
        import { prisma } from "${importPath(detectedLayout, editPagePath, prismaPath)}";
        import { revalidatePath } from "next/cache";
        import { redirect } from "next/navigation";
        import { SmartForm } from "${importPath(detectedLayout, editPagePath, smartFormPath)}";
        import { ${model.name}Resource } from "${importPath(detectedLayout, editPagePath, resourcePath)}";
        ${hasPasswordField ? `import { hashPassword } from "${importPath(detectedLayout, editPagePath, authPath)}";` : ""}
        import type { Prisma } from "@prisma/client";

        type PageProps = { params: Promise<{ id: string }> };

        export default async function Edit${model.name}Page({ params }: PageProps) {
          const routeParams = await params;
          const id = ${idTypeBase === "Int" ? "Number(routeParams.id)" : idTypeBase === "BigInt" ? "BigInt(routeParams.id)" : "routeParams.id"};
          const existing = await prisma.${model.name.toLowerCase()}.findUnique({
            where: { ${idName}: id }
          });
          if (!existing) return <div className="sb-card sb-empty-state">Record not found.</div>;

          async function update(formData: FormData) {
            "use server";
            const data: Prisma.${model.name}UncheckedUpdateInput = {
${fieldsForUI
  .map(
    (field) =>
      `              ${field.name}: ${formValueFor(
        field,
        `Prisma.${model.name}UncheckedUpdateInput`,
        "edit",
      )},`
  )
  .join("\n")}
            };
            await prisma.${model.name.toLowerCase()}.update({
              where: { ${idName}: id },
              data
            });
            revalidatePath("/admin/${plural}");
            redirect("/admin/${plural}");
          }

          const initialValues = Object.fromEntries(
            Object.entries(existing).map(([key, value]) => [
              key,
              ${hasPasswordField ? `["password", "passwordHash"].includes(key)
                ? ""
                : ` : ""}value instanceof Date
                ? value.toISOString().slice(0, 16)
                : value,
            ])
          );

          return (
            <SmartForm
              title="Edit ${model.name}"
              fields={${model.name}Resource.fields}
              initialValues={initialValues}
              submitLabel="Save"
              cancelHref="/admin/${plural}"
              action={update}
            />
          );
        }
      `;

      await writeGeneratedFile(listPagePath, listPage);
      await writeGeneratedFile(newPagePath, newPage);
      await writeGeneratedFile(editPagePath, editPage);
    }

    // registry.ts
    const existingResourceFiles = (await fs.pathExists(genDir))
      ? (await fs.readdir(genDir)).filter((file) =>
          file.endsWith("Resource.ts"),
        )
      : [];
    const selectedResourceFiles = pageModels.map(
      (selectedModel) => `${selectedModel.name}Resource.ts`,
    );
    const resourceFiles = [
      ...new Set([...existingResourceFiles, ...selectedResourceFiles]),
    ];
    const registryPath = path.join(outDir, "registry.ts");
    const overridesPath = path.join(outDir, "overrides.ts");

    const registryImports = resourceFiles
      .map((f) => {
        const n = f.replace("Resource.ts", "");
        return `import { ${n}Resource } from "${importPath(
          detectedLayout,
          registryPath,
          path.join(genDir, f),
        )}";`;
      })
      .join("\n");

    const registryArray = resourceFiles
      .map((f) => f.replace("Resource.ts", "Resource"))
      .join(",\n  ");

    const registryText = `
      // ${GENERATED_REGISTRY_MARKER}
      import { overrides, mergeResource } from "${importPath(
        detectedLayout,
        registryPath,
        overridesPath,
      )}";
      ${registryImports}

      const baseResources = [
        ${registryArray}
      ];

      export const resources = baseResources.map((res) => {
        const ov = (overrides as Record<string, unknown>)[res.resource] as Partial<typeof res> | undefined;
        return mergeResource(res, ov);
      });
    `;

    await writeGeneratedFile(
      registryPath,
      registryText,
      {
        allowUpdate: true,
        isSafeToUpdate: isSwitchboardRegistry,
      },
    );

    // Generate /admin layout + index that use the registry
    if (options.pages) {
      const adminRoot = path.join(appDir, "admin");
      const layoutPath = path.join(adminRoot, "layout.tsx");
      const indexPath = path.join(adminRoot, "page.tsx");

      const layout = adminLayoutTemplate(
        detectedLayout,
        layoutPath,
        registryPath,
      );


      const index = `
        // ${GENERATED_FILE_MARKER}
        import Link from "next/link";
        import { resources } from "${importPath(detectedLayout, indexPath, registryPath)}";

        export default function AdminIndex() {
          return (
            <section className="sb-page">
              <div className="sb-page-header">
                <div>
                  <p className="sb-eyebrow">Switchboard</p>
                  <h1 className="sb-page-title">Admin dashboard</h1>
                  <p className="sb-page-description">Choose a resource to view and manage its records.</p>
                </div>
              </div>
              <div className="sb-dashboard-grid">
                {resources.map((r) => (
                  <Link
                    className="sb-card sb-resource-card"
                    href={"/admin/" + r.resource.toLowerCase() + "s"}
                    key={r.resource}
                  >
                    <span className="sb-resource-card-title">{r.displayName}</span>
                    <span className="sb-resource-card-copy">View and manage {r.displayName.toLowerCase()}.</span>
                  </Link>
                ))}
              </div>
            </section>
          );
        }
      `;

      await writeGeneratedFile(layoutPath, layout);
      await writeGeneratedFile(indexPath, index);
    }

    return { layout: detectedLayout, results };
}
