// Generated by Switchboard. You may edit this file.
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { SmartForm } from "@/components/form/SmartForm";
import { TaskResource } from "@/switchboard/generated/TaskResource";

import { Prisma } from "@prisma/client";

function actionErrorMessage(error: unknown, operation: "save" | "delete") {
  console.error(`Switchboard failed to ${operation} Task:`, error);
  if (error instanceof SyntaxError) {
    return "A JSON field contains invalid JSON.";
  }
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    if (error.code === "P2002") {
      return "A record with that unique value already exists.";
    }
    if (error.code === "P2003") {
      return operation === "delete"
        ? "This record cannot be deleted because other records still reference it."
        : "A selected related record no longer exists.";
    }
    if (error.code === "P2025") return "This record no longer exists.";
  }
  return operation === "delete"
    ? "The record could not be deleted."
    : "The record could not be saved. Check the values and try again.";
}

export default async function NewTaskPage() {
  const [projectRecords, assigneeRecords] = await Promise.all([
    prisma.project.findMany({
      select: {
        id: true,
        name: true,
      },
      orderBy: { name: "asc" },
    }),
    prisma.user.findMany({
      select: {
        id: true,
        name: true,
      },
      orderBy: { name: "asc" },
    }),
  ]);
  const relationOptions = {
    projectId: projectRecords.map((record) => ({
      value: String(record.id),
      label: String(record.name ?? record.id),
    })),
    assigneeId: assigneeRecords.map((record) => ({
      value: String(record.id),
      label: String(record.name ?? record.id),
    })),
  };

  async function create(
    _previousState: { error?: string },
    formData: FormData,
  ) {
    "use server";
    try {
      const data: Prisma.TaskUncheckedCreateInput = {
        projectId: String(formData.get("projectId") ?? ""),
        title: String(formData.get("title") ?? ""),
        dueDate: formData.get("dueDate")
          ? new Date(String(formData.get("dueDate") ?? ""))
          : null,
        done: String(formData.get("done") ?? "") === "true",
        assigneeId: formData.get("assigneeId")
          ? String(formData.get("assigneeId") ?? "")
          : null,
      };
      await prisma.task.create({ data });
    } catch (error) {
      return { error: actionErrorMessage(error, "save") };
    }
    revalidatePath("/admin/tasks");
    redirect("/admin/tasks");
  }

  return (
    <SmartForm
      title="New Task"
      fields={TaskResource.fields}
      relationOptions={relationOptions}
      submitLabel="Create"
      cancelHref="/admin/tasks"
      action={create}
    />
  );
}
