// src/prisma/seed.ts
import { PrismaClient, Role, PostStatus, ProjectStatus } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // --- Users (keep your original ones) ---
  const ada = await prisma.user.upsert({
    where: { email: "ada@example.com" },
    update: {},
    create: { name: "Ada Lovelace", email: "ada@example.com", role: Role.ADMIN },
  });

  const grace = await prisma.user.upsert({
    where: { email: "grace@example.com" },
    update: {},
    create: { name: "Grace Hopper", email: "grace@example.com", role: Role.MANAGER },
  });

  const alan = await prisma.user.upsert({
    where: { email: "alan@example.com" },
    update: {},
    create: { name: "Alan Turing", email: "alan@example.com", role: Role.USER },
  });

  const john = await prisma.user.upsert({
    where: { email: "john@appleberry.com" },
    update: {},
    create: { name: "John Appleberry", email: "john@appleberry.com", role: Role.USER },
  });

  // --- Projects ---
  const projSwitchboard = await prisma.project.upsert({
    where: { id: "seed-proj-1" },
    update: {},
    create: {
      id: "seed-proj-1",
      name: "Switchboard Admin",
      description: "Internal admin panel scaffolding",
      status: ProjectStatus.ACTIVE,
      ownerId: ada.id,
    },
  });

  const projOls = await prisma.project.upsert({
    where: { id: "seed-proj-2" },
    update: {},
    create: {
      id: "seed-proj-2",
      name: "OneLineStory",
      description: "Public storytelling site",
      status: ProjectStatus.ON_HOLD,
      ownerId: grace.id,
    },
  });

  // --- Tasks ---
  await prisma.task.upsert({
    where: { id: "seed-task-1" },
    update: {},
    create: {
      id: "seed-task-1",
      projectId: projSwitchboard.id,
      title: "Generate pages from schema",
      assigneeId: alan.id,
      done: true,
    },
  });

  await prisma.task.upsert({
    where: { id: "seed-task-2" },
    update: {},
    create: {
      id: "seed-task-2",
      projectId: projSwitchboard.id,
      title: "Add registry + sidebar",
      assigneeId: ada.id,
      done: false,
    },
  });

  await prisma.task.upsert({
    where: { id: "seed-task-3" },
    update: {},
    create: {
      id: "seed-task-3",
      projectId: projOls.id,
      title: "Hook Switchboard into OLS",
      assigneeId: john.id,
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7), // in 7 days
      done: false,
    },
  });

  // --- Posts ---
  await prisma.post.upsert({
    where: { id: "seed-post-1" },
    update: {},
    create: {
      id: "seed-post-1",
      title: "Hello, Switchboard",
      content: "First post generated by the seed script.",
      status: PostStatus.PUBLISHED,
      authorId: ada.id,
    },
  });

  await prisma.post.upsert({
    where: { id: "seed-post-2" },
    update: {},
    create: {
      id: "seed-post-2",
      title: "Roadmap",
      content: "CLI → Pages → Package → OLS integration.",
      status: PostStatus.DRAFT,
      authorId: grace.id,
    },
  });
}

main()
  .then(async () => {
    console.log("Seed complete");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
