import { PrismaClient, Role, PostStatus, ProjectStatus } from "@prisma/client";

import { randomBytes, scryptSync } from "node:crypto";

const prisma = new PrismaClient();

function hashPassword(password) {
  const salt = randomBytes(16);
  const options = { N: 16384, r: 8, p: 1, maxmem: 64 * 1024 * 1024 };
  const hash = scryptSync(password, salt, 64, options);
  return [
    "scrypt",
    options.N,
    options.r,
    options.p,
    salt.toString("base64url"),
    hash.toString("base64url"),
  ].join("$");
}

async function main() {
  const localPasswordHash = hashPassword("password");
  // Users - seed (modify as needed)
  const ada = await prisma.user.upsert({
    where: { email: "ada@example.com" },
    update: {
      username: "admin",
      passwordHash: localPasswordHash,
      role: Role.ADMIN,
    },
    create: {
      name: "Ada Lovelace",
      username: "admin",
      email: "ada@example.com",
      passwordHash: localPasswordHash,
      role: Role.ADMIN,
    },
  });

  const grace = await prisma.user.upsert({
    where: { email: "grace@example.com" },
    update: { username: "grace", passwordHash: localPasswordHash },
    create: {
      name: "Grace Hopper",
      username: "grace",
      email: "grace@example.com",
      passwordHash: localPasswordHash,
      role: Role.MANAGER,
    },
  });

  const alan = await prisma.user.upsert({
    where: { email: "alan@example.com" },
    update: { username: "alan", passwordHash: localPasswordHash },
    create: {
      name: "Alan Turing",
      username: "alan",
      email: "alan@example.com",
      passwordHash: localPasswordHash,
      role: Role.USER,
    },
  });

  const john = await prisma.user.upsert({
    where: { email: "john@appleberry.com" },
    update: { username: "john", passwordHash: localPasswordHash },
    create: {
      name: "John Appleberry",
      username: "john",
      email: "john@appleberry.com",
      passwordHash: localPasswordHash,
      role: Role.USER,
    },
  });

  // Projects
  const projSwitchboard = await prisma.project.upsert({
    where: { id: "seed-proj-1" },
    update: {},
    create: {
      id: "seed-proj-1",
      name: "Switchboard Admin",
      description: "Internal admin panel scaffolding",
      status: ProjectStatus.ACTIVE,
      ownerId: ada.id,
    },
  });

  const projOls = await prisma.project.upsert({
    where: { id: "seed-proj-2" },
    update: {},
    create: {
      id: "seed-proj-2",
      name: "OneLineStory",
      description: "Public storytelling site",
      status: ProjectStatus.ON_HOLD,
      ownerId: grace.id,
    },
  });

  // Tasks
  await prisma.task.upsert({
    where: { id: "seed-task-1" },
    update: {},
    create: {
      id: "seed-task-1",
      projectId: projSwitchboard.id,
      title: "Generate pages from schema",
      assigneeId: alan.id,
      done: true,
    },
  });

  await prisma.task.upsert({
    where: { id: "seed-task-2" },
    update: {},
    create: {
      id: "seed-task-2",
      projectId: projSwitchboard.id,
      title: "Add registry + sidebar",
      assigneeId: ada.id,
      done: false,
    },
  });

  await prisma.task.upsert({
    where: { id: "seed-task-3" },
    update: {},
    create: {
      id: "seed-task-3",
      projectId: projOls.id,
      title: "Hook Switchboard into OLS",
      assigneeId: john.id,
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7), // in 7 days
      done: false,
    },
  });

  // Posts
  await prisma.post.upsert({
    where: { id: "seed-post-1" },
    update: {},
    create: {
      id: "seed-post-1",
      title: "Hello, Switchboard",
      content: "First post generated by the seed script.",
      status: PostStatus.PUBLISHED,
      authorId: ada.id,
    },
  });

  await prisma.post.upsert({
    where: { id: "seed-post-2" },
    update: {},
    create: {
      id: "seed-post-2",
      title: "Roadmap",
      content: "CLI → Pages → Package → OLS integration.",
      status: PostStatus.DRAFT,
      authorId: grace.id,
    },
  });
}

main()
  .then(async () => {
    console.log("Seed complete");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
