// Generated by Switchboard. You may edit this file.
"use server";

import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import { prisma } from "@/lib/prisma";
import {
  createSessionToken,
  sessionCookieOptions,
  SWITCHBOARD_SESSION_COOKIE,
  verifyPassword,
} from "@/switchboard/auth";

export async function login(formData: FormData) {
  const credential = String(formData.get("credential") ?? "").trim();
  const password = String(formData.get("password") ?? "");
  if (!credential || !password) {
    redirect("/admin/login?error=missing");
  }

  const user = await prisma.user.findUnique({
    where: { username: credential },
    select: {
      id: true,
      passwordHash: true,
      role: true,
    },
  });
  const passwordMatches = await verifyPassword(
    password,
    user?.passwordHash ?? "",
  );
  if (!user || !passwordMatches || String(user.role) !== "ADMIN") {
    redirect("/admin/login?error=invalid");
  }

  const cookieStore = await cookies();
  cookieStore.set(
    SWITCHBOARD_SESSION_COOKIE,
    createSessionToken(String(user.id)),
    sessionCookieOptions(),
  );
  redirect("/admin");
}
