// Generated by Switchboard. This registry is updated by switchboard generate.
import { overrides, mergeResource } from "@/switchboard/overrides";
import { PostResource } from "@/switchboard/generated/PostResource";
import { UserResource } from "@/switchboard/generated/UserResource";

const baseResources = [PostResource, UserResource];

export const resources = baseResources.map((res) => {
  const ov = (overrides as Record<string, unknown>)[res.resource] as
    | Partial<typeof res>
    | undefined;
  return mergeResource(res, ov);
});
