// Generated by Switchboard. You may edit this file.
import { NextRequest, NextResponse } from "next/server";

import {
  sessionCookieOptions,
  SWITCHBOARD_SESSION_COOKIE,
} from "@/switchboard/auth";

export function GET(request: NextRequest) {
  const response = NextResponse.redirect(new URL("/admin/login", request.url));
  response.cookies.set(SWITCHBOARD_SESSION_COOKIE, "", {
    ...sessionCookieOptions(),
    expires: new Date(0),
    maxAge: 0,
  });
  return response;
}
