// Generated by Switchboard. You may edit this file.
import "./switchboard.css";
import Link from "next/link";
import { headers } from "next/headers";
import { resources } from "@/switchboard/registry";

export default async function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const requestHeaders = await headers();
  const isLoginPage = requestHeaders.get("x-switchboard-login-page") === "1";

  if (isLoginPage) {
    return <div className="sb-login-shell">{children}</div>;
  }

  return (
    <div className="sb-admin-shell">
      <header className="sb-admin-header">
        <nav className="sb-admin-nav">
          <Link className="sb-admin-brand" href="/admin">
            Switchboard
          </Link>
          <div className="sb-admin-nav-actions">
            <Link className="sb-admin-home-link" href="/">
              Back to site
            </Link>
            <Link
              className="sb-button sb-button-secondary"
              href="/admin/logout"
            >
              Logout
            </Link>
          </div>
        </nav>
      </header>
      <main className="sb-admin-main">
        <aside className="sb-admin-sidebar">
          <nav className="sb-resource-nav" aria-label="Admin resources">
            <h2 className="sb-resource-nav-title">Resources</h2>
            <ul className="sb-resource-list">
              {resources.map((resource) => (
                <li key={resource.resource}>
                  <Link
                    className="sb-resource-link"
                    href={"/admin/" + resource.resource.toLowerCase() + "s"}
                  >
                    {resource.displayName}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </aside>
        <section className="sb-admin-content">{children}</section>
      </main>
    </div>
  );
}
