import fs from "fs-extra";

export const GENERATED_FILE_MARKER =
  "Generated by Switchboard. You may edit this file.";
export const GENERATED_REGISTRY_MARKER =
  "Generated by Switchboard. This registry is updated by switchboard generate.";

export function hasGeneratedFileMarker(content) {
  return (
    content.includes(GENERATED_FILE_MARKER) ||
    content.includes(GENERATED_REGISTRY_MARKER)
  );
}

export async function planFileAction({
  path,
  content,
  force = false,
  allowUpdate = false,
  isSafeToUpdate = hasGeneratedFileMarker,
}) {
  if (!(await fs.pathExists(path))) {
    return { action: "create", path, content };
  }

  const stat = await fs.stat(path);
  if (!stat.isFile()) {
    return {
      action: "error",
      path,
      content,
      reason: "the target exists and is not a file",
    };
  }

  const existingContent = await fs.readFile(path, "utf8");
  if (existingContent === content) {
    return { action: "unchanged", path, content };
  }
  if (force) {
    return { action: "overwrite", path, content };
  }
  if (allowUpdate && isSafeToUpdate(existingContent)) {
    return { action: "update", path, content };
  }
  return {
    action: "skip",
    path,
    content,
    reason: "it already exists; use --force to overwrite",
  };
}

export async function applyFileAction(plan, { dryRun = false } = {}) {
  if (plan.action === "error") {
    throw new Error(`Cannot write "${plan.path}": ${plan.reason}.`);
  }
  if (
    !dryRun &&
    ["create", "update", "overwrite"].includes(plan.action)
  ) {
    await fs.outputFile(plan.path, plan.content, "utf8");
  }
  return plan;
}

export function describeFileAction(plan, displayPath, { dryRun = false } = {}) {
  if (plan.action === "error") {
    return `Error ${displayPath}: ${plan.reason}`;
  }
  if (plan.action === "unchanged") {
    return `Unchanged ${displayPath}`;
  }
  if (plan.action === "skip") {
    return `${dryRun ? "Would skip" : "Skipped"} ${displayPath} because ${plan.reason}`;
  }

  const verbs = {
    create: dryRun ? "Would create" : "Created",
    update: dryRun ? "Would update" : "Updated",
    overwrite: dryRun ? "Would overwrite" : "Overwrote",
  };
  return `${verbs[plan.action]} ${displayPath}`;
}
