// Generated by Switchboard. You may edit this file.
import {
  createHmac,
  randomBytes,
  scrypt as scryptCallback,
  timingSafeEqual,
} from "node:crypto";

const KEY_LENGTH = 64;
const SCRYPT_OPTIONS = {
  N: 16384,
  r: 8,
  p: 1,
  maxmem: 64 * 1024 * 1024,
};
const SESSION_DURATION_SECONDS = 60 * 60 * 8;

export const SWITCHBOARD_SESSION_COOKIE = "switchboard_session";

type SessionPayload = {
  userId: string;
  role: "ADMIN";
  expiresAt: number;
};

function sessionSecret() {
  const secret = process.env.SWITCHBOARD_SESSION_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error(
      "SWITCHBOARD_SESSION_SECRET is required and must be at least 32 characters.",
    );
  }
  return secret;
}

function scryptPassword(password: string, salt: Buffer) {
  return new Promise<Buffer>((resolve, reject) => {
    scryptCallback(
      password,
      salt,
      KEY_LENGTH,
      SCRYPT_OPTIONS,
      (error, derivedKey) => {
        if (error) reject(error);
        else resolve(derivedKey);
      },
    );
  });
}

function signature(value: string) {
  return createHmac("sha256", sessionSecret())
    .update(value)
    .digest("base64url");
}

export function createSessionToken(userId: string) {
  const payload: SessionPayload = {
    userId,
    role: "ADMIN",
    expiresAt: Math.floor(Date.now() / 1000) + SESSION_DURATION_SECONDS,
  };
  const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url");
  return encoded + "." + signature(encoded);
}

export function sessionCookieOptions() {
  return {
    httpOnly: true,
    sameSite: "lax" as const,
    secure: process.env.NODE_ENV === "production",
    path: "/",
    maxAge: SESSION_DURATION_SECONDS,
  };
}

export async function hashPassword(password: string) {
  const salt = randomBytes(16);
  const derivedKey = await scryptPassword(password, salt);
  return [
    "scrypt",
    SCRYPT_OPTIONS.N,
    SCRYPT_OPTIONS.r,
    SCRYPT_OPTIONS.p,
    salt.toString("base64url"),
    Buffer.from(derivedKey).toString("base64url"),
  ].join("$");
}

export async function verifyPassword(password: string, storedHash: string) {
  const [algorithm, n, r, p, saltValue, hashValue] = storedHash.split("$");
  const validFormat =
    algorithm === "scrypt" &&
    n === String(SCRYPT_OPTIONS.N) &&
    r === String(SCRYPT_OPTIONS.r) &&
    p === String(SCRYPT_OPTIONS.p);
  const salt = validFormat
    ? Buffer.from(saltValue ?? "", "base64url")
    : Buffer.alloc(16);
  const expected = validFormat
    ? Buffer.from(hashValue ?? "", "base64url")
    : Buffer.alloc(KEY_LENGTH);
  const comparable =
    validFormat && salt.length === 16 && expected.length === KEY_LENGTH;
  const actual = await scryptPassword(
    password,
    comparable ? salt : Buffer.alloc(16),
  );
  return comparable && timingSafeEqual(expected, Buffer.from(actual));
}
