// Auto-generated by Switchboard CLI
import { PostResource } from "@/switchboard/generated/PostResource";
import { ProjectResource } from "@/switchboard/generated/ProjectResource";
import { TaskResource } from "@/switchboard/generated/TaskResource";
import { UserResource } from "@/switchboard/generated/UserResource";
export const resources = [
  PostResource,
  ProjectResource,
  TaskResource,
  UserResource,
] as const;
