// Auto-generated by Switchboard CLI (safe to keep under version control)
import { overrides, mergeResource } from "@/switchboard/overrides";
import { PostResource } from "@/switchboard/generated/PostResource";
import { ProjectResource } from "@/switchboard/generated/ProjectResource";
import { TaskResource } from "@/switchboard/generated/TaskResource";
import { UserResource } from "@/switchboard/generated/UserResource";

const baseResources = [
  PostResource,
  ProjectResource,
  TaskResource,
  UserResource,
];

export const resources = baseResources.map((res) => {
  const ov = (overrides as Record<string, unknown>)[res.resource] as
    | Partial<typeof res>
    | undefined;
  return mergeResource(res, ov);
});
