// Generated by Switchboard. You may edit this file.
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { SmartForm } from "@/components/form/SmartForm";
import { UserResource } from "@/switchboard/generated/UserResource";
import { hashPassword } from "@/switchboard/auth";
import { Prisma } from "@prisma/client";

function actionErrorMessage(error: unknown, operation: "save" | "delete") {
  console.error(`Switchboard failed to ${operation} User:`, error);
  if (error instanceof SyntaxError) {
    return "A JSON field contains invalid JSON.";
  }
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    if (error.code === "P2002") {
      return "A record with that unique value already exists.";
    }
    if (error.code === "P2003") {
      return operation === "delete"
        ? "This record cannot be deleted because other records still reference it."
        : "A selected related record no longer exists.";
    }
    if (error.code === "P2025") return "This record no longer exists.";
  }
  return operation === "delete"
    ? "The record could not be deleted."
    : "The record could not be saved. Check the values and try again.";
}

export default async function NewUserPage() {
  const relationOptions = {};

  async function create(
    _previousState: { error?: string },
    formData: FormData,
  ) {
    "use server";
    try {
      const data: Prisma.UserUncheckedCreateInput = {
        name: String(formData.get("name") ?? ""),
        username: formData.get("username")
          ? String(formData.get("username") ?? "")
          : null,
        email: String(formData.get("email") ?? ""),
        passwordHash: await hashPassword(
          String(formData.get("passwordHash") ?? ""),
        ),
        role: formData.get("role")
          ? (String(
              formData.get("role") ?? "",
            ) as Prisma.UserUncheckedCreateInput["role"])
          : undefined,
      };
      await prisma.user.create({ data });
    } catch (error) {
      return { error: actionErrorMessage(error, "save") };
    }
    revalidatePath("/admin/users");
    redirect("/admin/users");
  }

  return (
    <SmartForm
      title="New User"
      fields={UserResource.fields}
      relationOptions={relationOptions}
      submitLabel="Create"
      cancelHref="/admin/users"
      action={create}
    />
  );
}
