// Generated by Switchboard. You may edit this file.
import { NextRequest, NextResponse } from "next/server";

const COOKIE_NAME = "switchboard_session";
const LOGIN_PATH = "/admin/login";

function sessionSecret() {
  const secret = process.env.SWITCHBOARD_SESSION_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error(
      "SWITCHBOARD_SESSION_SECRET is required and must be at least 32 characters.",
    );
  }
  return secret;
}

function decodeBase64Url(value: string) {
  const base64 = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, "=");
  return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
}

async function hasValidAdminSession(request: NextRequest) {
  const token = request.cookies.get(COOKIE_NAME)?.value;
  if (!token) return false;
  const [payloadValue, signatureValue] = token.split(".");
  if (!payloadValue || !signatureValue) return false;

  try {
    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(sessionSecret()),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"],
    );
    const validSignature = await crypto.subtle.verify(
      "HMAC",
      key,
      decodeBase64Url(signatureValue),
      new TextEncoder().encode(payloadValue),
    );
    if (!validSignature) return false;

    const payload = JSON.parse(
      new TextDecoder().decode(decodeBase64Url(payloadValue)),
    ) as { role?: string; expiresAt?: number };
    return (
      payload.role === "ADMIN" &&
      typeof payload.expiresAt === "number" &&
      payload.expiresAt > Math.floor(Date.now() / 1000)
    );
  } catch {
    return false;
  }
}

export async function middleware(request: NextRequest) {
  sessionSecret();
  const isLoginPage = request.nextUrl.pathname === LOGIN_PATH;
  const hasSession = await hasValidAdminSession(request);

  if (isLoginPage) {
    if (hasSession) {
      return NextResponse.redirect(new URL("/admin", request.url));
    }
    const requestHeaders = new Headers(request.headers);
    requestHeaders.set("x-switchboard-login-page", "1");
    return NextResponse.next({
      request: { headers: requestHeaders },
    });
  }

  if (!hasSession) {
    return NextResponse.redirect(new URL(LOGIN_PATH, request.url));
  }

  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-switchboard-login-page", "0");
  return NextResponse.next({
    request: { headers: requestHeaders },
  });
}

export const config = {
  matcher: ["/admin/:path*"],
};
